### ISSUE TITLE
ShB Relic weapon sync bug

### ISSUE THREAD

**Issue by Rodanco** [KhloeLeclair/GearsetHelperPlugin#1]
When i use the sync option for 475ilv (for TEA fight), for some reason its entirely ignoring the stats i put on the weapon.
Idk if it was reported already, but i did not found an issue like this here on github

![image](https://user-images.githubusercontent.com/14005991/173162625-8fe0680d-e838-47b3-9641-b584f8099427.png)

**Comment by KhloeLeclair** [comment]
Forgot to mark this closed when I released c97cf824f6dbf2401bfcbe0ade425bed99671316 to fix it.
